name: flutter_plugin
description: A new Flutter plugin.
version: 0.0.1
author: Pratik Sherdiwala

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.10.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  plugin:
    platforms:
      android:
        package: com.knoxpo.flutter_plugin
        pluginClass: FlutterPlugin

